function [writeKeys] = INIFileKey(INIData,ProcessData)

x = ProcessData.Transponder_ENU + INIData.OutPut_FloorRandn*randn(size(ProcessData.Transponder_ENU));
atd=[INIData.Forward,INIData.Rightward,INIData.Downward];
inifile(INIData.Iniaddress,'new');
interpret1=cellstr("# Array_cent :   'cntpos_E'  'cntpos_N'  'cntpos_U'");
interpret2=cellstr("# MT_Pos     :   'stapos_E'  'stapos_N'  'stapos_U'   'sigma_E'   'sigma_N'   'sigma_U'   'cov_NU'    'cov_UE'    'cov_EN'");
interpret3=cellstr("# ANT_to_TD  :   'forward'  'rightward'  'downward'   'sigma_F'   'sigma_R'   'sigma_D'   'cov_RD'    'cov_DF'    'cov_FR'");
MTStations=[];
for j=1:INIData.TransponderNum
    MTPos{j,1}='Model-parameter';MTPos{j,2}='';
    MTPos{j,3}=[' ',INIData.TransponderName{j},'_dPos    '];
    MTPos{j,4}=[x(j,:),3.0010,3.0010,3.0010,0,0,0];
    MTStations=[MTStations,' ',INIData.TransponderName{j}];
end

writeKeys = {
    'Obs-parameter','',' Site_name','Data';...
    'Obs-parameter','',' Campaign',INIData.Campaign;...
    'Obs-parameter','',' Date(UTC)',[num2str(INIData.LaunchRT(1)),'-',num2str(INIData.LaunchRT(2),'%02d'),'-',num2str(INIData.LaunchRT(3),'%02d')];...
    'Obs-parameter','',' Date(jday)',[num2str(INIData.LaunchRT(1)),'-',num2str(day(datetime(INIData.LaunchRT(1),INIData.LaunchRT(2),INIData.LaunchRT(3)),'dayofyear'),'%03d')];...
    'Obs-parameter','',' Ref.Frame','ITRF2014';...
    'Obs-parameter','',' SoundSpeed',INIData.FileSVPAddress;...
    'Data-file','',' datacsv',INIData.FileOBSAddress;...
    'Data-file','',' N_shot',num2str(INIData.Obs_Shot);...
    'Data-file','',' used_shot','0';...
    'Site-parameter','',' Latitude0   ','34.96166667';...
    'Site-parameter','',' Longitude0  ','139.26333333';...
    'Site-parameter','',' Height0     ','43.00';...
    'Site-parameter','',' Stations    ',MTStations;...
    'Site-parameter','',interpret1{:},'';...
    'Site-parameter','',' Center_ENU  ',mean(x,1);...
    'Model-parameter','',interpret2{:},''};
m = size(writeKeys,1);
for i=1:size(MTPos,1)
    for j=1:size(MTPos,2)
        writeKeys{m+i,j}=MTPos{i,j};
    end
end
writeKeys1 = {
    'Model-parameter','',' dCentPos    ',zeros(1,9);...
    'Model-parameter','',interpret3{:},'';...
    'Model-parameter','',' ATDoffset   ',[atd,0,0,0,0,0,0];...
    'Model-parameter','','newline','';...
    'Model-parameter','','newline','';...
    };
m = size(writeKeys,1);
for i=1:size(writeKeys1,1)
    for j=1:size(writeKeys1,2)
        writeKeys{m+i,j}=writeKeys1{i,j};
    end
end
end

